### PR TITLE
Fix #30

### LINKED ISSUE #30: [BUG] Compress of v2 does not work if corpus is not split beforehand
**Describe the bug**
The toolchain fails to compress the corpus if the corpus is not split. The output is as follows:

```
[2023-03-02T13:45:15Z ERROR oscar_tools::ops::compress] Err(Io(Os { code: 20, kind: NotADirectory, message: "Not a directory" }))
[2023-03-02T13:45:15Z ERROR oscar_tools::ops::compress] Err(Io(Os { code: 20, kind: NotADirectory, message: "Not a directory" }))
[2023-03-02T13:45:15Z ERROR oscar_tools::ops::compress] Err(Io(Os { code: 20, kind: NotADirectory, message: "Not a directory" }))
[2023-03-02T13:45:15Z ERROR oscar_tools::ops::compress] Err(Io(Os { code: 20, kind: NotADirectory, message: "Not a directory" }))
[2023-03-02T13:45:15Z ERROR oscar_tools::ops::compress] Err(Io(Os { code: 20, kind: NotADirectory, message: "Not a directory" }))
```

**To Reproduce**
1. Run `oscar-tools v2 compress [source] [dest]` on a unsplit corpus.

**Expected behavior**
The corpus is properly compressed even if it is not split.

**Desktop (please complete the following information):**
 - OS: Linux 4.18.0-372
 - Version: main c54c7fd24f36109799ef31efe598db4a568b7675

### PR DESCRIPTION
**Pull request by pjox**
Fixes #30 and actually compresses any possible tree structure.

### CODE REVIEW

**Comment by pjox** [comment]
Now it works 😄

**Comment by Uinelj** [comment]
I had a test failing on my side, so I set the number of threads to `1` on the incriminated test.

**Comment by pjox** [comment]
Weird, on my machine it was not failing 🤔

**Review by Uinelj — APPROVED** [review]

**Comment by Uinelj** [comment]
With `rustc 1.68.2 (9eb3afe9e 2023-03-27)`.. I don't know, either way it's better to avoid instantiating the threadpool in the tests, since instantiating it twice will lead to errors! Another approach would be to destroy it or to use a scoped one.

**Pull request merged**
